### ISSUE TITLE
seconds_convertor.py

### ISSUE THREAD

**Issue by kensorrells** [derekmoyes/python-stuff#2]
So I was running some basic tests and I found that there may be a conversion issue taking place. If you run a calculator and put in 601 seconds it should come out to be 10 minutes and, 1 second.
Instead it runs as 10 hours and, 1 minute and, 1 second.

**Comment by derekmoyes** [comment]
This is a valid issue, I've tested it, thanks!

**Comment by derekmoyes** [comment]
Fixed! 

Commit https://github.com/derekmoyes/python-stuff/commit/23dc84980fa299f64b5cb07c58420a1e7c583c5a fixes the issue with the extra second, as well as added an entire block of code (can't remember either days or months) that was missing. 

Also added a bunch of debug stuff, since I was struggling with the math a bit.
